#!/bin/bash

pushd ../../MDUV380_firmware/application/include/user_interface/languages/src
gcc -Wall -O2 -I../ -o languages_builder languages_builder.c
./languages_builder
popd

if [ -f ../../MDUV380_firmware/MDUV380_FW/OpenMDUV380.bin ]; then
    zip -j ../../MDUV380_firmware/MDUV380_FW/OpenMDUV380.zip ../../MDUV380_firmware/MDUV380_FW/OpenMDUV380.bin ../../MDUV380_firmware/application/include/user_interface/languages/src/*.gla
fi

if [ -f ../../MDUV380_firmware/JA_MDUV380_FW/OpenMDUV380_Japanese.bin ]; then
    zip -j ../../MDUV380_firmware/JA_MDUV380_FW/OpenMDUV380_Japanese.zip ../../MDUV380_firmware/JA_MDUV380_FW/OpenMDUV380_Japanese.bin ../../MDUV380_firmware/application/include/user_interface/languages/src/*.gla
fi

if [ -f ../../MDUV380_firmware/DM1701_FW/OpenDM1701.bin ]; then
    zip -j ../../MDUV380_firmware/DM1701_FW/OpenDM1701.zip ../../MDUV380_firmware/DM1701_FW/OpenDM1701.bin ../../MDUV380_firmware/application/include/user_interface/languages/src/*.gla
fi

if [ -f ../../MDUV380_firmware/JA_DM1701_FW/OpenDM1701_Japanese.bin ]; then
    zip -j ../../MDUV380_firmware/JA_DM1701_FW/OpenDM1701_Japanese.zip ../../MDUV380_firmware/JA_DM1701_FW/OpenDM1701_Japanese.bin ../../MDUV380_firmware/application/include/user_interface/languages/src/*.gla
fi

if [ -f ../../MDUV380_firmware/MDUV380_10W_PLUS_FW/OpenMDUV380_10W_PLUS.bin ]; then
    zip -j ../../MDUV380_firmware/MDUV380_10W_PLUS_FW/OpenMDUV380_10W_PLUS.zip ../../MDUV380_firmware/MDUV380_10W_PLUS_FW/OpenMDUV380_10W_PLUS.bin ../../MDUV380_firmware/application/include/user_interface/languages/src/*.gla
fi

if [ -f ../../MDUV380_firmware/JA_MDUV380_10W_PLUS_FW/OpenMDUV380_10W_PLUS_Japanese.bin ]; then
    zip -j ../../MDUV380_firmware/JA_MDUV380_10W_PLUS_FW/OpenMDUV380_10W_PLUS_Japanese.zip ../../MDUV380_firmware/JA_MDUV380_10W_PLUS_FW/OpenMDUV380_10W_PLUS_Japanese.bin ../../MDUV380_firmware/application/include/user_interface/languages/src/*.gla
fi

if [ -f ../../MDUV380_firmware/RT84_FW/OpenRT84.bin ]; then
    zip -j ../../MDUV380_firmware/RT84_FW/OpenRT84.zip ../../MDUV380_firmware/RT84_FW/OpenRT84.bin ../../MDUV380_firmware/application/include/user_interface/languages/src/*.gla
fi

if [ -f ../../MDUV380_firmware/JA_RT84_FW/OpenRT84_Japanese.bin ]; then
    zip -j ../../MDUV380_firmware/JA_RT84_FW/OpenRT84_Japanese.zip ../../MDUV380_firmware/JA_RT84_FW/OpenRT84_Japanese.bin ../../MDUV380_firmware/application/include/user_interface/languages/src/*.gla
fi

