#!/usr/bin/env bash

function dummy_codec_cleaner {
    local input_file=""
    local output_file=""

    while [[ $# -gt 0 ]]; do
        case "$1" in
            -i)
                input_file="$2"
                shift 2
                ;;
            -o)
                output_file="$2"
                shift 2
                ;;
            *)
                echo "Illegal command line argument: $1"
                exit 1
                ;;
        esac
    done

    if [[ -z "$input_file" || -z "$output_file" ]]; then
        echo "Both -i INPUT_FILE and -o OUTPUT_FILE are mandatory."
        exit 1
    fi

    cp "$input_file" "$output_file"
}

OS=`uname -s`

case "$OS" in
    "Linux")
	../tools/codec_cleaner.Linux "$@"
	;;
    "Darwin")
	dummy_codec_cleaner "$@"
	;;
    *)
	;;
esac
